#ifndef __CONFIG_H
#define __CONFIG_H


/*------------------------电流发送允许---------------------*/
/**
 * @brief 用于快速注释电流发送
 * @note  
 * @param 
 */

#define GIMBAL_YAW_SENT
#define GIMBAL_PITCH_SENT    
#define SHOOT_SEND
#define TRIGGER_SENT
/*--------------------------云台参数----------------------------*/

//角度
#define NORMAL_BIG_PITCH_ANGLE 1.32f//正常模式下大pitch的目标角度
#define FOLD_BIG_PITCH_ANGLE 1.96f//折叠模式下大pitch的目标角度
#define FOLD_SMALL_YAW_ANGLE 1000//折叠模式下小yaw的目标角度（ecd）
#define FOLD_SMALL_PITCH_ANGLE -140//折叠模式下小pitch的目标角度
#define NORMAL_SMALL_PITCH_ANGLE -170//刚进入折叠模式下小pitch的目标角度

#define YAW_LIMIT_ANGLE 1024 //大小yaw限位角度，45度
#define BIG_YAW_VISION_CONTROL_ANGLE 0.53f //大yaw视觉控制角度阈值
#define PITCH_LIMIT 20.0f

#define FOLD_TIME_MAX 2000//折叠计时


#define CRUISE_YAW_SPEED 0.01f//巡航小yaw转动速度
#define CRUISE_PITCH_SPEED 0.01f//巡航pitch转动速度
#define CRUISE_PITCH_MAX 15.0f//巡航pitch最大角度
#define CRUISE_PITCH_MIN -37.0f//巡航pitch最小角度
//系统识别
#define PID_YAW_ANGLE_RECO_MODE 0
#define PID_YAW_ANGLE_RECO_KP 0.7f//0.4
#define PID_YAW_ANGLE_RECO_KI 0
#define PID_YAW_ANGLE_RECO_KD 0
#define PID_YAW_ANGLE_RECO_IMAX_OUT 0
#define PID_YAW_ANGLE_RECO_MAX_OUT 5//5

#define PID_YAW_SPEED_RECO_MODE 0
#define PID_YAW_SPEED_RECO_KP 30.0f//20
#define PID_YAW_SPEED_RECO_KI 0.0f
#define PID_YAW_SPEED_RECO_KD 0
#define PID_YAW_SPEED_RECO_IMAX_OUT 10
#define PID_YAW_SPEED_RECO_MAX_OUT 50

#define PID_PITCH_ANGLE_RECO_MODE 0
#define PID_PITCH_ANGLE_RECO_KP 0.4f//0.4
#define PID_PITCH_ANGLE_RECO_KI 0
#define PID_PITCH_ANGLE_RECO_KD 0  
#define PID_PITCH_ANGLE_RECO_IMAX_OUT 0
#define PID_PITCH_ANGLE_RECO_MAX_OUT 5//5

#define PID_PITCH_SPEED_RECO_MODE 0
#define PID_PITCH_SPEED_RECO_KP 20.0f//20
#define PID_PITCH_SPEED_RECO_KI 0
#define PID_PITCH_SPEED_RECO_KD 0
#define PID_PITCH_SPEED_RECO_IMAX_OUT 0
#define PID_PITCH_SPEED_RECO_MAX_OUT 50
//无视觉(正常模式)
#define PID_YAW_ANGLE_MODE 0
#define PID_YAW_ANGLE_KP 0.7f
#define PID_YAW_ANGLE_KI 0
#define PID_YAW_ANGLE_KD 0
#define PID_YAW_ANGLE_IMAX_OUT 0
#define PID_YAW_ANGLE_MAX_OUT 7

#define PID_YAW_SPEED_MODE 0
#define PID_YAW_SPEED_KP 0.7f//0.8
#define PID_YAW_SPEED_KI 0
#define PID_YAW_SPEED_KD 0
#define PID_YAW_SPEED_IMAX_OUT 0
#define PID_YAW_SPEED_MAX_OUT 5

#define PID_PITCH_ANGLE_MODE 0
#define PID_PITCH_ANGLE_KP 0.4f
#define PID_PITCH_ANGLE_KI 0
#define PID_PITCH_ANGLE_KD 0.1f
#define PID_PITCH_ANGLE_IMAX_OUT 0
#define PID_PITCH_ANGLE_MAX_OUT 7.0f

#define PID_PITCH_SPEED_MODE 0
#define PID_PITCH_SPEED_KP 0.6f
#define PID_PITCH_SPEED_KI 0
#define PID_PITCH_SPEED_KD 0.0f
#define PID_PITCH_SPEED_IMAX_OUT 0
#define PID_PITCH_SPEED_MAX_OUT 5.0f



#define PID_MOTOR_ANGLE_MODE 0
#define PID_MOTOR_ANGLE_KP 18
#define PID_MOTOR_ANGLE_KI 0.01
#define PID_MOTOR_ANGLE_KD 0
#define PID_MOTOR_ANGLE_IOUT_MAX 1
#define PID_MOTOR_ANGLE_OUT_MAX 7

#define PID_MOTOR_SPEED_MODE 0
#define PID_MOTOR_SPEED_KP 0.17f
#define PID_MOTOR_SPEED_KI 0
#define PID_MOTOR_SPEED_KD 0
#define PID_MOTOR_SPEED_IOUT_MAX 0
#define PID_MOTOR_SPEED_OUT_MAX 5

#define PID_PITCH_MOTOR_ANGLE_MODE 0
#define PID_PITCH_MOTOR_ANGLE_KP 0.5
#define PID_PITCH_MOTOR_ANGLE_KI 0.0f
#define PID_PITCH_MOTOR_ANGLE_KD 0
#define PID_PITCH_MOTOR_ANGLE_IOUT_MAX 0
#define PID_PITCH_MOTOR_ANGLE_OUT_MAX 4

#define PID_PITCH_MOTOR_SPEED_MODE 0
#define PID_PITCH_MOTOR_SPEED_KP 0.3f
#define PID_PITCH_MOTOR_SPEED_KI 0
#define PID_PITCH_MOTOR_SPEED_KD 0
#define PID_PITCH_MOTOR_SPEED_IOUT_MAX 0
#define PID_PITCH_MOTOR_SPEED_OUT_MAX 3
//调头
#define PID_YAW_ANGLE_MODE_DT 0
#define PID_YAW_ANGLE_KP_DT 0.7f
#define PID_YAW_ANGLE_KI_DT 0
#define PID_YAW_ANGLE_KD_DT 0
#define PID_YAW_ANGLE_IMAX_OUT_DT 0
#define PID_YAW_ANGLE_MAX_OUT_DT 7

#define PID_YAW_SPEED_MODE_DT 0
#define PID_YAW_SPEED_KP_DT 0.7f//0.8
#define PID_YAW_SPEED_KI_DT 0
#define PID_YAW_SPEED_KD_DT 0
#define PID_YAW_SPEED_IMAX_OUT_DT 0
#define PID_YAW_SPEED_MAX_OUT_DT 3.0f

#define PID_PITCH_ANGLE_MODE_DT 0
#define PID_PITCH_ANGLE_KP_DT 0.6f
#define PID_PITCH_ANGLE_KI_DT 0
#define PID_PITCH_ANGLE_KD_DT 0
#define PID_PITCH_ANGLE_IMAX_OUT_DT 0
#define PID_PITCH_ANGLE_MAX_OUT_DT 7.0f

#define PID_PITCH_SPEED_MODE_DT 0
#define PID_PITCH_SPEED_KP_DT 0.9f
#define PID_PITCH_SPEED_KI_DT 0
#define PID_PITCH_SPEED_KD_DT 0
#define PID_PITCH_SPEED_IMAX_OUT_DT 0
#define PID_PITCH_SPEED_MAX_OUT_DT 5.0f



//装甲板
#define PID_YAW_VISION_ARMOR_ANGLE_MODE 0
#define PID_YAW_VISION_ARMOR_ANGLE_KP 0.4f//0.4
#define PID_YAW_VISION_ARMOR_ANGLE_KI 0.001f
#define PID_YAW_VISION_ARMOR_ANGLE_KD 0
#define PID_YAW_VISION_ARMOR_ANGLE_IMAX_OUT 0.0f
#define PID_YAW_VISION_ARMOR_ANGLE_MAX_OUT 10.0f

#define PID_YAW_VISION_ARMOR_SPEED_MODE 0
#define PID_YAW_VISION_ARMOR_SPEED_KP 1.0f
#define PID_YAW_VISION_ARMOR_SPEED_KI 0.001f
#define PID_YAW_VISION_ARMOR_SPEED_KD 0
#define PID_YAW_VISION_ARMOR_SPEED_IMAX_OUT 0.0f
#define PID_YAW_VISION_ARMOR_SPEED_MAX_OUT 4.0f

#define PID_PITCH_VISION_ARMOR_ANGLE_MODE 0
#define PID_PITCH_VISION_ARMOR_ANGLE_KP 0.5f
#define PID_PITCH_VISION_ARMOR_ANGLE_KI 0.003f
#define PID_PITCH_VISION_ARMOR_ANGLE_KD 0
#define PID_PITCH_VISION_ARMOR_ANGLE_IMAX_OUT 0.0f//1
#define PID_PITCH_VISION_ARMOR_ANGLE_MAX_OUT 5

#define PID_PITCH_VISION_ARMOR_SPEED_MODE 0
#define PID_PITCH_VISION_ARMOR_SPEED_KP 0.9f
#define PID_PITCH_VISION_ARMOR_SPEED_KI 0.007f
#define PID_PITCH_VISION_ARMOR_SPEED_KD 0
#define PID_PITCH_VISION_ARMOR_SPEED_IMAX_OUT 0.0f
#define PID_PITCH_VISION_ARMOR_SPEED_MAX_OUT 3


//BUFF
#define PID_YAW_VISION_BUFF_ANGLE_MODE 0
#define PID_YAW_VISION_BUFF_ANGLE_KP  0.6f
#define PID_YAW_VISION_BUFF_ANGLE_KI 0.001f
#define PID_YAW_VISION_BUFF_ANGLE_KD 0
#define PID_YAW_VISION_BUFF_ANGLE_IMAX_OUT 0.0f
#define PID_YAW_VISION_BUFF_ANGLE_MAX_OUT 7

#define PID_YAW_VISION_BUFF_SPEED_MODE 0
#define PID_YAW_VISION_BUFF_SPEED_KP 0.4f
#define PID_YAW_VISION_BUFF_SPEED_KI 0.001
#define PID_YAW_VISION_BUFF_SPEED_KD 0
#define PID_YAW_VISION_BUFF_SPEED_IMAX_OUT 1.0f
#define PID_YAW_VISION_BUFF_SPEED_MAX_OUT 3

#define PID_PITCH_VISION_BUFF_ANGLE_MODE 0
#define PID_PITCH_VISION_BUFF_ANGLE_KP 0.45
#define PID_PITCH_VISION_BUFF_ANGLE_KI 0.001f
#define PID_PITCH_VISION_BUFF_ANGLE_KD 0
#define PID_PITCH_VISION_BUFF_ANGLE_IMAX_OUT 1.0f
#define PID_PITCH_VISION_BUFF_ANGLE_MAX_OUT 7

#define PID_PITCH_VISION_BUFF_SPEED_MODE 0
#define PID_PITCH_VISION_BUFF_SPEED_KP 1.2f
#define PID_PITCH_VISION_BUFF_SPEED_KI 0
#define PID_PITCH_VISION_BUFF_SPEED_KD 0
#define PID_PITCH_VISION_BUFF_SPEED_IMAX_OUT 0
#define PID_PITCH_VISION_BUFF_SPEED_MAX_OUT 3

//巡航
#define PID_YAW_ANGLE_CRUISE_MODE 0
#define PID_YAW_ANGLE_CRUISE_KP 0.7f
#define PID_YAW_ANGLE_CRUISE_KI 0
#define PID_YAW_ANGLE_CRUISE_KD 0
#define PID_YAW_ANGLE_CRUISE_IMAX_OUT 0
#define PID_YAW_ANGLE_CRUISE_MAX_OUT 7

#define PID_YAW_SPEED_CRUISE_MODE 0
#define PID_YAW_SPEED_CRUISE_KP 0.7f//0.8
#define PID_YAW_SPEED_CRUISE_KI 0
#define PID_YAW_SPEED_CRUISE_KD 0
#define PID_YAW_SPEED_CRUISE_IMAX_OUT 0
#define PID_YAW_SPEED_CRUISE_MAX_OUT 5

#define PID_PITCH_ANGLE_CRUISE_MODE 0
#define PID_PITCH_ANGLE_CRUISE_KP 0.4f
#define PID_PITCH_ANGLE_CRUISE_KI 0
#define PID_PITCH_ANGLE_CRUISE_KD 0.1f
#define PID_PITCH_ANGLE_CRUISE_IMAX_OUT 0
#define PID_PITCH_ANGLE_CRUISE_MAX_OUT 7.0f

#define PID_PITCH_SPEED_CRUISE_MODE 0
#define PID_PITCH_SPEED_CRUISE_KP 0.6f
#define PID_PITCH_SPEED_CRUISE_KI 0
#define PID_PITCH_SPEED_CRUISE_KD 0.0f
#define PID_PITCH_SPEED_CRUISE_IMAX_OUT 0
#define PID_PITCH_SPEED_CRUISE_MAX_OUT 5.0f


//低通滤波参数
#define LowPass_YAW_KEY_TIME    0.28f
#define LowPass_PITCH_KEY_TIME   0.28f
#define LowPass_YAW_KEY_NUM    1.8f
#define LowPass_PITCH_KEY_NUM   1.8f

//低通滤波参数
#define LowPass_YAW_VISION_TIME    0.28f
#define LowPass_PITCH_VISION_TIME   0.28f
#define LowPass_YAW_VISION_NUM    1.5f
#define LowPass_PITCH_VISION_NUM   1.8f


//视觉yaw前馈（装甲板）（速度）
#define VISION_YAW_ALPHA 0.12//0.06
#define VISION_YAW_BELTA 0.0f
#define VISION_YAW_OUTMAX   0.5f  //   0.8f      
//视觉pitch前馈（装甲板）(速度)
#define VISION_PITCH_ALPHA 2.0f
#define VISION_PITCH_BELTA 0.0f
#define VISION_PITCH_OUTMAX    5     //      15.0f
//视觉pitch前馈（装甲板）（加速度）
#define VISION_PITCH_SPEED_ALPHA 0
#define VISION_PITCH_SPEED_BELTA 0
#define VISION_PITCH_SPEED_OUTMAX 0
//视觉yaw前馈（装甲板）（加速度）
#define VISION_YAW_SPEED_ALPHA 0.0008f//0.0005f
#define VISION_YAW_SPEED_BELTA 0.0f
#define VISION_YAW_SPEED_OUTMAX   0.8f //0.6   


//视觉yaw前馈（符）
#define VISION_YAW_ALPHA_MECHANIASM 7.5f
#define VISION_YAW_BELTA_MECHANIASM 0.0f
#define VISION_YAW_OUTMAX_MECHANIASM           25.0f
//视觉pitch前馈（符）
#define VISION_PITCH_ALPHA_MECHANIASM 2.0f
#define VISION_PITCH_BELTA_MECHANIASM 0.0f
#define VISION_PITCH_OUTMAX_MECHANIASM 15.0f

/*-------------------------灵敏度-------------------------*/
#define SENSITIVITY_CHASSIS_RC_X  8.0
#define SENSITIVITY_CHASSIS_RC_Y  8.0
#define SENSITIVITY_CHASSIS_KEYBOARD_X  2000
#define SENSITIVITY_CHASSIS_KEYBOARD_Y  2000

#define SENSITIVITY_YAW_RC 0.0006f
#define SENSITIVITY_YAW_MOUSE 0.0003f
#define SENSITIVITY_PITCH_RC 0.0001f
#define SENSITIVITY_PITCH_MOUSE 0.0006f
#define MOUSE_MAX 4000



/*-------------------------摩擦轮参数---------------------------*/

#define PID_FRICTIONGEAR_LEFT_MODE 0
#define PID_FRICTIONGEAR_LEFT_KP 5
#define PID_FRICTIONGEAR_LEFT_KI 0
#define PID_FRICTIONGEAR_LEFT_KD 0
#define PID_FRICTIONGEAR_LEFT_MAXIOUT 0
#define PID_FRICTIONGEAR_LEFT_MAXOUT 10000

#define PID_FRICTIONGEAR_RIGHT_MODE 0
#define PID_FRICTIONGEAR_RIGHT_KP 5
#define PID_FRICTIONGEAR_RIGHT_KI 0
#define PID_FRICTIONGEAR_RIGHT_KD 0
#define PID_FRICTIONGEAR_RIGHT_MAXIOUT 0
#define PID_FRICTIONGEAR_RIGHT_MAXOUT 10000

#define SHOOT_AVERAGE_SPEED 22
#define SHOOT_MAX_SPEED 23
#define SHOOT_MIN_SPEED 22
#define SHOOT_SPEED_ADD 20
#define SHOOT_SPEED_MINUS 80



#endif
