#ifndef __CONFIG_H
#define __CONFIG_H


/*------------------------电流发送允许---------------------*/
/**
 * @brief 用于快速注释电流发送
 * @note  
 * @param 
 */

#define GIMBAL_YAW_SENT
#define CHASSIS_SENT
//#define BAT 
#define CAP
/*-------------------------控制模式--------------------------------*/
#define INFANTRY_CTRL 0
#define	SENTRY_CTRL 1

#define DETECT_NORMAL   0
#define DETECT_NONE     1
//操作模式
#define CONTROL_RC_CTRL 0
#define CONTROL_KEYBOARD_CTRL 1
//云台模式
#define GIMBAL_IDLE 0
#define GIMBAL_NORMAL 1
#define GIMBAL_VISION 2
#define GIMBAL_FOLD 3
#define GIMBAL_CRUISE 4
//视觉模式
#define VISION_CLOSE 0
#define VISION_ARMOR 1
#define VISION_SMALL_BUFF 2
#define VISION_BIG_BUFF 3
//摩擦轮模式
#define SHOOT_IDLE 0
#define SHOOT_OPEN 1
//拨弹盘模式
#define TRIGGER_IDLE 0
#define TRIGGER_SINGLE 1
#define TRIGGER_LONG 2
#define TRIGGER_BACK 3

#define STUCK_ERR 0//卡弹
#define	STUCK_NORMAL 1//正常

//底盘模式
#define CHASSIS_IDLE 0
#define CHASSIS_FOLLOW 1
#define CHASSIS_TOP 2
//底盘加速度模式
#define CHASSIS_SPEED_NORMAL 0
#define CHASSIS_SPEED_SHIFT 1
#define CHASSIS_SPEED_FLY 2
/*--------------------------云台参数----------------------------*/


#define FOLD_SMALL_YAW_ANGLE 1000//折叠模式下小yaw的目标角度ecd
#define YAW_LIMIT_ANGLE 1024 //大小yaw限位45度
#define BIG_YAW_VISION_CONTROL_ANGLE 683 //大yaw视觉控制角度阈值

//无视觉(正常模式)

#define PID_BIG_YAW_ANGLE_MODE 0
#define PID_BIG_YAW_ANGLE_KP 0.7f
#define PID_BIG_YAW_ANGLE_KI 0
#define PID_BIG_YAW_ANGLE_KD 0
#define PID_BIG_YAW_ANGLE_IMAX_OUT 0
#define PID_BIG_YAW_ANGLE_MAX_OUT 7.0f

#define PID_BIG_YAW_SPEED_MODE 0
#define PID_BIG_YAW_SPEED_KP 0.8f
#define PID_BIG_YAW_SPEED_KI 0
#define PID_BIG_YAW_SPEED_KD 0
#define PID_BIG_YAW_SPEED_IMAX_OUT 0
#define PID_BIG_YAW_SPEED_MAX_OUT 4.0f

//掉头
#define PID_BIG_YAW_ANGLE_MODE_DT 0
#define PID_BIG_YAW_ANGLE_KP_DT 1.8f
#define PID_BIG_YAW_ANGLE_KI_DT 0
#define PID_BIG_YAW_ANGLE_KD_DT 0
#define PID_BIG_YAW_ANGLE_IMAX_OUT_DT 0
#define PID_BIG_YAW_ANGLE_MAX_OUT_DT 7

#define PID_BIG_YAW_SPEED_MODE_DT 0
#define PID_BIG_YAW_SPEED_KP_DT 1.5f
#define PID_BIG_YAW_SPEED_KI_DT 0
#define PID_BIG_YAW_SPEED_KD_DT 0
#define PID_BIG_YAW_SPEED_IMAX_OUT_DT 0
#define PID_BIG_YAW_SPEED_MAX_OUT_DT 4


//折叠模式

#define PID_BIG_YAW_FOLD_ANGLE_MODE 0
#define PID_BIG_YAW_FOLD_ANGLE_KP 0.7f
#define PID_BIG_YAW_FOLD_ANGLE_KI 0
#define PID_BIG_YAW_FOLD_ANGLE_KD 0
#define PID_BIG_YAW_FOLD_ANGLE_IMAX_OUT 0
#define PID_BIG_YAW_FOLD_ANGLE_MAX_OUT 7

#define PID_BIG_YAW_FOLD_SPEED_MODE 0
#define PID_BIG_YAW_FOLD_SPEED_KP 1.4f
#define PID_BIG_YAW_FOLD_SPEED_KI 0
#define PID_BIG_YAW_FOLD_SPEED_KD 0
#define PID_BIG_YAW_FOLD_SPEED_IMAX_OUT 0
#define PID_BIG_YAW_FOLD_SPEED_MAX_OUT 5


//装甲板

#define PID_BIG_YAW_VISION_ARMOR_ANGLE_MODE 0
#define PID_BIG_YAW_VISION_ARMOR_ANGLE_KP 0.7f
#define PID_BIG_YAW_VISION_ARMOR_ANGLE_KI 0.001
#define PID_BIG_YAW_VISION_ARMOR_ANGLE_KD 0
#define PID_BIG_YAW_VISION_ARMOR_ANGLE_IMAX_OUT 0
#define PID_BIG_YAW_VISION_ARMOR_ANGLE_MAX_OUT 7.0f

#define PID_BIG_YAW_VISION_ARMOR_SPEED_MODE 0
#define PID_BIG_YAW_VISION_ARMOR_SPEED_KP 1.0f
#define PID_BIG_YAW_VISION_ARMOR_SPEED_KI 0.0001
#define PID_BIG_YAW_VISION_ARMOR_SPEED_KD 0
#define PID_BIG_YAW_VISION_ARMOR_SPEED_IMAX_OUT 0
#define PID_BIG_YAW_VISION_ARMOR_SPEED_MAX_OUT 4.0f

//BUFF


#define PID_BIG_YAW_VISION_BUFF_ANGLE_MODE 0
#define PID_BIG_YAW_VISION_BUFF_ANGLE_KP 0.6
#define PID_BIG_YAW_VISION_BUFF_ANGLE_KI 0
#define PID_BIG_YAW_VISION_BUFF_ANGLE_KD 0
#define PID_BIG_YAW_VISION_BUFF_ANGLE_IMAX_OUT 0
#define PID_BIG_YAW_VISION_BUFF_ANGLE_MAX_OUT 7

#define PID_BIG_YAW_VISION_BUFF_SPEED_MODE 0
#define PID_BIG_YAW_VISION_BUFF_SPEED_KP 0.8
#define PID_BIG_YAW_VISION_BUFF_SPEED_KI 0
#define PID_BIG_YAW_VISION_BUFF_SPEED_KD 0
#define PID_BIG_YAW_VISION_BUFF_SPEED_IMAX_OUT 0
#define PID_BIG_YAW_VISION_BUFF_SPEED_MAX_OUT 4


//低通滤波参数
#define LowPass_YAW_KEY_TIME    0.28f
#define LowPass_PITCH_KEY_TIME   0.28f
#define LowPass_YAW_KEY_NUM    1.8f
#define LowPass_PITCH_KEY_NUM   1.8f

//低通滤波参数
#define LowPass_YAW_VISION_TIME    0.28f
#define LowPass_PITCH_VISION_TIME   0.28f
#define LowPass_YAW_VISION_NUM    1.5f
#define LowPass_PITCH_VISION_NUM   1.8f


//视觉yaw前馈（装甲板）
#define VISION_YAW_ALPHA 7.0f
#define VISION_YAW_BELTA 0.0f
#define VISION_YAW_OUTMAX  0.9f    //        25.0f
//视觉pitch前馈（装甲板）
#define VISION_PITCH_ALPHA 2.0f
#define VISION_PITCH_BELTA 0.0f
#define VISION_PITCH_OUTMAX    5     //      15.0f

//视觉yaw前馈（符）
#define VISION_YAW_ALPHA_MECHANIASM 7.5f
#define VISION_YAW_BELTA_MECHANIASM 0.0f
#define VISION_YAW_OUTMAX_MECHANIASM           25.0f
//视觉pitch前馈（符）
#define VISION_PITCH_ALPHA_MECHANIASM 2.0f
#define VISION_PITCH_BELTA_MECHANIASM 0.0f
#define VISION_PITCH_OUTMAX_MECHANIASM 15.0f
/*---------------------底盘参数--------------------------*/

#define FRONT_SET_1 -173.4f//
#define FRONT_SET_2  6.6f//
#define FRONT_SET_SENTRY 0.0f//

#define CHASSIS_MAX_CURRENT 16300
#define FOLLOW_MAX_CURRENT 4000
#define FL 3//左前
#define RL 0//左后
#define FR 2//右前
#define RR 1//右后

#define PID_MOTOR_MODE 0
#define PID_MOTOR_KP 10.0f
#define PID_MOTOR_KI 0
#define PID_MOTOR_KD 0
#define PID_MOTOR_IOUT_MAX 0
#define PID_MOTOR_OUT_MAX 16000

#define PID_YAW_FOLLOW_MODE 0
#define PID_YAW_FOLLOW_KP 60
#define PID_YAW_FOLLOW_KI 0
#define PID_YAW_FOLLOW_KD 0
#define PID_YAW_FOLLOW_IOUT_MAX 0
#define PID_YAW_FOLLOW_OUT_MAX 4000


////底盘键鼠速度(有电容)
#define SPEED_45W_CAP 2600
#define SPEED_50W_CAP 2700
#define SPEED_55W_CAP 2750
#define SPEED_60W_CAP 3100
#define SPEED_65W_CAP 3150
#define SPEED_70W_CAP 3225
#define SPEED_75W_CAP 3300
#define SPEED_80W_CAP 3350
#define SPEED_85W_CAP 3415
#define SPEED_90W_CAP 3490
#define SPEED_95W_CAP 3560
#define SPEED_100W_CAP 3620
#define SPEED_120W_CAP 3750
#define SPEED_DEFAULT_CAP 2860
#define SPEED_SHIFT_CAP 5000
#define SPEED_FLY_CAP 4750

#define SPEED_ADD_CAP  0

//底盘键鼠速度(无电容)
#define SPEED_45W_BAT 2400
#define SPEED_50W_BAT 2600
#define SPEED_55W_BAT 3025
#define SPEED_60W_BAT 3025
#define SPEED_65W_BAT 3080
#define SPEED_70W_BAT 3135
#define SPEED_75W_BAT 3190
#define SPEED_80W_BAT 3245
#define SPEED_85W_BAT 3300
#define SPEED_90W_BAT 3410
#define SPEED_95W_BAT 3500
#define SPEED_100W_BAT 3630
#define SPEED_120W_BAT 3630
#define SPEED_DEFAULT_BAT 4000
#define SPEED_SHIFT_BAT 3200
#define SPEED_FLY_BAT 4250

#define SPEED_ADD_BAT  700

//底盘陀螺速度(有电容)
#define TOP_SPEED_45W_CAP 5000
#define TOP_SPEED_50W_CAP 5000
#define TOP_SPEED_55W_CAP 5000
#define TOP_SPEED_60W_CAP 5000
#define TOP_SPEED_65W_CAP 6000
#define TOP_SPEED_70W_CAP 6000
#define TOP_SPEED_75W_CAP 6000
#define TOP_SPEED_80W_CAP 6000
#define TOP_SPEED_85W_CAP 6000
#define TOP_SPEED_90W_CAP 6500
#define TOP_SPEED_95W_CAP 6500
#define TOP_SPEED_100W_CAP 6500
#define TOP_SPEED_120W_CAP 7000
#define TOP_SPEED_DEFAULT_CAP 5000
#define TOP_SPEED_SHIFT_CAP 7000
#define TOP_SPEED_FLY_CAP 6000


#define TOP_SPEED_ADD_CAP  1000

//底盘陀螺速度(无电容)
#define TOP_SPEED_45W_BAT 4000
#define TOP_SPEED_50W_BAT 4000
#define TOP_SPEED_55W_BAT 4000
#define TOP_SPEED_60W_BAT 4000
#define TOP_SPEED_65W_BAT 4000
#define TOP_SPEED_70W_BAT 4000
#define TOP_SPEED_75W_BAT 4000
#define TOP_SPEED_80W_BAT 4000
#define TOP_SPEED_85W_BAT 4000
#define TOP_SPEED_90W_BAT 4000
#define TOP_SPEED_95W_BAT 4000
#define TOP_SPEED_100W_BAT 4000
#define TOP_SPEED_120W_BAT 4000
#define TOP_SPEED_DEFAULT_BAT 4000
#define TOP_SPEED_SHIFT_BAT 3500
#define TOP_SPEED_FLY_BAT 3500

#define TOP_SPEED_ADD_BAT  1400


//底盘加速度限制
#define CHASSIS_SPEED_LIMIT_NORMAL 25.0f
#define CHASSIS_SPEED_LIMIT_SHIFT 45.0f
#define CHASSIS_SPEED_LIMIT_FLY 40.0f

/*-------------------------灵敏度-------------------------*/
#define SENSITIVITY_CHASSIS_RC_X  15.0
#define SENSITIVITY_CHASSIS_RC_Y  15.0
#define SENSITIVITY_CHASSIS_KEYBOARD_X  2000
#define SENSITIVITY_CHASSIS_KEYBOARD_Y  2000

#define SENSITIVITY_YAW_RC 0.0003f
#define SENSITIVITY_YAW_MOUSE 0.0003f
#define SENSITIVITY_PITCH_RC 0.00003f
#define SENSITIVITY_PITCH_MOUSE 0.0003f



#endif
